version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "4000:4000"
    environment:
      -  DB_URL=postgresql://flask_application:password@flask_db:5432/cha_de_casa_nova
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=flask_application
      - POSTGRES_DB=cha_de_casa_nova
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
