version: "3.9"

services:
  site_db:
    container_name: site_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=site_application
      - POSTGRES_DB=cha_de_casa_nova
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
