jwt:
  secret: ak12kj431l24hksjhdflka21l4

spring:
  application:
    name: housewarming-party
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTC
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimumIdle: 1
      maximum-pool-size: 5
  sql:
    init:
      platform: postgres
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  servlet:
    port: 8080
    context-path: /api/housewarming-party
