jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: housewarming-party
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTC
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/cha_de_casa_nova"
    username: site_application
    password: password
    hikari:
      minimumIdle: 1
      maximum-pool-size: 5
  sql:
    init:
      platform: postgres
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  servlet:
    port: 8080
    context-path: /api/housewarming-party
