services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://site_db:5432/housewarming_party
      DB_HOST: jdbc:postgresql://site_db:5432/housewarming_party
      DB_NAME: housewarming_party
      DB_USERNAME: site_application
      DB_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - site_db

  site_db:
    container_name: site_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=site_application
      - POSTGRES_DB=housewarming_party
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
