services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - site_db

  site_db:
    container_name: site_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=site_application
      - POSTGRES_DB=cha_de_casa_nova
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
